# Agent Repair Pipeline — 2WikiMultiHopQA

**ICLR Experiment Pipeline — Colab A100-80GB + Qwen2.5-32B-Instruct-AWQ**

| Stage | What it does | ~Time (A100-80GB, 500 Qs) |
|---|---|---|
| 0 | Download 2WikiMultiHopQA, create folders | 1 min |
| 1 | ReAct trajectory generation (Qwen2.5-32B-Instruct-AWQ) | ~1-2 h |
| 2 | Step-level uncertainty scoring | ~1-2 h |
| 3 | 72B judge error annotation | ~1-2 h |
| 4 | Localization scoring (+ cascade-aware rules) | < 1 min |
| 5 | 126 repair strategies (backtrack × nudge type ablation) | ~4-6 h |
| 6 | Tables, stats, figures, ablation analysis | < 1 min |

**Every stage is resumable** — if Colab disconnects, re-run the cell and it picks up where it left off.

---
## 0. Setup

In [1]:
# Verify GPU — should show A100
!nvidia-smi --query-gpu=name,memory.total --format=csv,noheader

/bin/bash: line 1: nvidia-smi: command not found

In [1]:
# Mount Google Drive for persistent storage
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_2wikimultihopqa.yaml'

if not os.path.exists(REPO_DIR):
    !git clone https://github.com/kishormorol/agent-repair.git {REPO_DIR}
else:
    !cd {REPO_DIR} && git pull

os.chdir(REPO_DIR)
print(f'Working directory: {os.getcwd()}')

Cloning into '/content/agent-repair'...
remote: Enumerating objects: 333, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 333 (delta 9), reused 3 (delta 1), pack-reused 313 (from 1)
Receiving objects: 100% (333/333), 4.86 MiB | 20.49 MiB/s, done.
Resolving deltas: 100% (168/168), done.
Working directory: /content/agent-repair

In [3]:
# Check Colab's CUDA version first
!nvcc --version 2>/dev/null || echo "nvcc not found"
!python -c "import torch; print(f'torch CUDA: {torch.version.cuda}')" 2>/dev/null || echo "torch not installed yet"
!nvidia-smi | grep "CUDA Version"

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
torch CUDA: 12.8
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |

In [4]:
# Install vLLM — pinned to 0.19.0 (last version with CUDA 12 default wheels)
# vLLM >= 0.20 ships CUDA 13 wheels which don't work on Colab's CUDA 12.x
!pip uninstall -y vllm 2>/dev/null
!pip install -q "vllm==0.19.0" 2>&1 | tail -5

# Install remaining dependencies
!pip install -q "transformers>=4.57.0" "tokenizers>=0.21.0" accelerate \
    huggingface_hub datasets scipy scikit-learn pandas pyarrow \
    pyyaml tqdm matplotlib seaborn statsmodels 2>&1 | tail -3

print('\n--- Installation complete ---')

google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.6 which is incompatible.
google-adk 2.4.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.4.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.6 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.

--- Installation complete ---

In [5]:
# Quick sanity check: can vLLM see the GPU?
import torch, vllm
print(f'torch:  {torch.__version__}')
print(f'vLLM:   {vllm.__version__}')
print(f'CUDA:   {torch.version.cuda}')
print(f'GPU:    {torch.cuda.get_device_name(0)}')
print(f'VRAM:   {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

torch:  2.10.0+cu128
vLLM:   0.19.0
CUDA:   12.8
GPU:    NVIDIA A100-SXM4-80GB
VRAM:   85.1 GB

In [6]:
# Clear previous data
import shutil, os
drive_base = '/content/drive/MyDrive/agent-repair-2wikimultihopqa'
for d in ['outputs', 'data/processed']:
    p = os.path.join(drive_base, d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
for d in ['outputs', 'data/processed']:
    p = os.path.join('/content/agent-repair', d)
    if os.path.exists(p):
        shutil.rmtree(p)
        print(f'Cleared {p}')
print('Ready for fresh run with 2WikiMultiHopQA')

Ready for fresh run with 2WikiMultiHopQA

---
## Smoke Test (20 questions, ~10-15 min)

**Run this first** to verify everything works before committing A100 units to the full 500-question run.

In [7]:
stages = ['run_setup', 'run_generate', 'run_uncertainty', 'run_annotate',
          'run_localize', 'run_repair', 'run_eval']

for stage in stages:
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG} --limit 20
    print()

============================================================
  run_setup
============================================================
03:56:20 | INFO    | setup | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
03:56:20 | INFO    | setup | Dataset: 2wikimultihopqa (file: 2wikimultihop_dev.json)
03:56:20 | INFO    | setup | Downloading 2wikimultihopqa via registry download function...
`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'framolfese/2WikiMultihopQA' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
README.md: 5.46kB [00:00, 22.0MB/s]
data/train-00000-of-00002.parquet: 100% 166M/166M [00:03<00:00, 43.3MB/s]
data/train-00001-of-00002.parquet: 100% 165M/165M [00:03<00:00, 43.5MB/s]
data/validation-00000-of-00001.parquet: 100% 29.5M/29.5M [00:01<00:00, 27.2MB/s]
data/test-00000-of-00001.parquet: 100% 28.0M/28.0M [00:00<00:00, 28.8MB/s]
Generating train split: 100% 167454/167454 [00:02<00:00, 76013.14 examples/s]
Generating validation split: 100% 12576/12576 [00:00<00:00, 72895.12 examples/s]
Generating test split: 100% 12576/12576 [00:00<00:00, 76277.39 examples/s]
  Loaded 2WikiMultiHopQA from framolfese/2WikiMultihopQA
03:56:44 | INFO    | setup | Downloaded 12576 records for 2wikimultihopqa.
03:56:45 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-2wikimultihopqa/data/raw/2wikimultihop_dev.json (64.2 MB, 12576 questions)
03:56:45 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-2wikimultihopqa


============================================================
  run_generate
============================================================
03:56:46 | INFO    | stage1 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
03:56:46 | INFO    | stage1 | Dataset: 2wikimultihopqa (env: WikiMultiHopEnv)
03:56:47 | INFO    | stage1 | Pool: 500 questions
03:56:47 | INFO    | stage1 | To process: 20 of 20 (0 already done)
03:56:51 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-31 03:56:54.286103: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 03:56:54.356643: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tokenizer_config.json: 7.30kB [00:00, 30.0MB/s]
vocab.json: 2.78MB [00:00, 113MB/s]
merges.txt: 1.67MB [00:00, 158MB/s]
tokenizer.json: 7.03MB [00:00, 195MB/s]
INFO 07-31 03:57:07 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
config.json: 100% 841/841 [00:00<00:00, 9.21MB/s]
INFO 07-31 03:57:27 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-31 03:57:27 [model.py:1678] Using max model len 8192
INFO 07-31 03:57:27 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-31 03:57:27 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
model.safetensors.index.json: 143kB [00:00, 360MB/s]
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.15it/s]
INFO 07-31 03:57:29 [vllm.py:790] Asynchronous scheduling is enabled.
generation_config.json: 100% 243/243 [00:00<00:00, 2.72MB/s]
WARNING 07-31 03:57:30 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=8860) INFO 07-31 03:57:48 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=8860) INFO 07-31 03:57:48 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:38565 backend=nccl
(EngineCore pid=8860) INFO 07-31 03:57:48 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=8860) INFO 07-31 03:57:49 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=8860) INFO 07-31 03:57:50 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=8860) INFO 07-31 03:57:50 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=8860) INFO 07-31 03:57:50 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=8860) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=8860) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
model-00003-of-00005.safetensors:   0% 0.00/3.95G [00:00<?, ?B/s]
model-00004-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:   0% 0.00/3.98G [00:00<?, ?B/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00005-of-00005.safetensors:   0% 0.00/3.48G [00:00<?, ?B/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:   2% 67.0M/3.95G [00:01<01:42, 37.7MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:   8% 335M/3.95G [00:02<00:21, 169MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:   8% 335M/3.98G [00:02<00:30, 121MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00005-of-00005.safetensors:   8% 268M/3.48G [00:02<00:28, 111MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:   2% 67.1M/3.94G [00:02<02:39, 24.3MB/s]
model-00003-of-00005.safetensors:  10% 402M/3.95G [00:03<00:22, 158MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  10% 403M/3.98G [00:03<00:28, 124MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00005-of-00005.safetensors:  10% 335M/3.48G [00:03<00:30, 104MB/s]
model-00004-of-00005.safetensors:  10% 402M/3.98G [00:03<00:26, 134MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  12% 470M/3.98G [00:03<00:27, 126MB/s]
model-00004-of-00005.safetensors:  17% 670M/3.98G [00:04<00:15, 214MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  20% 805M/3.95G [00:04<00:14, 221MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  10% 401M/3.94G [00:04<00:32, 108MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  11% 434M/3.94G [00:04<00:31, 111MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  13% 537M/3.98G [00:05<00:46, 73.9MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  27% 1.07G/3.95G [00:06<00:15, 188MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  22% 872M/3.98G [00:09<00:35, 86.7MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  39% 1.54G/3.95G [00:09<00:15, 157MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  42% 1.68G/3.95G [00:16<00:29, 75.8MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  31% 1.21G/3.94G [00:16<00:46, 59.1MB/s]
model-00004-of-00005.safetensors:  30% 1.21G/3.98G [00:16<00:41, 66.3MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  53% 2.08G/3.95G [00:17<00:17, 109MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  44% 1.75G/3.94G [00:17<00:19, 111MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  22% 872M/3.98G [00:19<00:35, 86.7MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00005-of-00005.safetensors:  27% 939M/3.48G [00:19<00:25, 101MB/s]
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  39% 1.54G/3.98G [00:20<00:35, 69.2MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  49% 1.95G/3.94G [00:20<00:19, 104MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  63% 2.48G/3.95G [00:21<00:14, 104MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  53% 2.08G/3.94G [00:24<00:25, 71.7MB/s]
model-00003-of-00005.safetensors:  70% 2.75G/3.95G [00:25<00:12, 94.6MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  60% 2.35G/3.94G [00:27<00:22, 71.6MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  76% 3.02G/3.95G [00:29<00:11, 82.5MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  65% 2.56G/3.94G [00:29<00:15, 86.9MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  67% 2.63G/3.94G [00:29<00:15, 87.2MB/s]
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  83% 3.29G/3.95G [00:32<00:08, 80.4MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  72% 2.83G/3.94G [00:32<00:13, 81.9MB/s]
model-00003-of-00005.safetensors:  88% 3.49G/3.95G [00:36<00:06, 67.6MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  77% 3.03G/3.94G [00:36<00:13, 68.0MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors:  95% 3.76G/3.95G [00:40<00:02, 65.8MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00003-of-00005.safetensors: 100% 3.95G/3.95G [00:41<00:00, 95.0MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00002-of-00005.safetensors:  83% 3.29G/3.98G [00:42<00:09, 76.3MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00005-of-00005.safetensors: 100% 3.48G/3.48G [00:44<00:00, 77.5MB/s]
(EngineCore pid=8860)
model-00004-of-00005.safetensors:  91% 3.62G/3.98G [00:45<00:04, 78.7MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors:  96% 3.77G/3.94G [00:45<00:02, 82.2MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00001-of-00005.safetensors: 100% 3.94G/3.94G [00:45<00:00, 87.0MB/s]
(EngineCore pid=8860)
model-00004-of-00005.safetensors: 100% 3.98G/3.98G [00:46<00:00, 86.0MB/s]
(EngineCore pid=8860)
(EngineCore pid=8860)
model-00002-of-00005.safetensors: 100% 3.98G/3.98G [00:46<00:00, 85.5MB/s]
(EngineCore pid=8860) INFO 07-31 03:58:39 [weight_utils.py:581] Time spent downloading weights for Qwen/Qwen2.5-32B-Instruct-AWQ: 47.267084 seconds
Loading safetensors checkpoint shards: 100% 5/5 [00:06<00:00,  1.23s/it]
(EngineCore pid=8860) INFO 07-31 03:58:45 [default_loader.py:384] Loading weights took 6.21 seconds
(EngineCore pid=8860) INFO 07-31 03:58:50 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 59.439171 seconds
(EngineCore pid=8860) INFO 07-31 03:59:09 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=8860) INFO 07-31 03:59:09 [backends.py:1111] Dynamo bytecode transform time: 18.54 s
(EngineCore pid=8860) INFO 07-31 03:59:15 [backends.py:372] Cache the graph of compile range (1, 8192) for later use
(EngineCore pid=8860) INFO 07-31 03:59:24 [backends.py:390] Compiling a graph for compile range (1, 8192) takes 13.97 s
(EngineCore pid=8860) INFO 07-31 03:59:29 [decorators.py:640] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=8860) INFO 07-31 03:59:29 [monitor.py:48] torch.compile took 38.86 s in total
(EngineCore pid=8860) INFO 07-31 03:59:33 [monitor.py:76] Initial profiling/warmup run took 3.23 s
(EngineCore pid=8860) INFO 07-31 03:59:43 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=8860) INFO 07-31 03:59:43 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=8860) INFO 07-31 03:59:46 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=8860) INFO 07-31 03:59:47 [gpu_worker.py:436] Available KV cache memory: 51.42 GiB
(EngineCore pid=8860) INFO 07-31 03:59:47 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=8860) INFO 07-31 03:59:47 [kv_cache_utils.py:1319] GPU KV cache size: 210,608 tokens
(EngineCore pid=8860) INFO 07-31 03:59:47 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.71x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.11it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.52it/s]
(EngineCore pid=8860) INFO 07-31 04:00:00 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=8860) INFO 07-31 04:00:00 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=8860) INFO 07-31 04:00:00 [core.py:283] init engine (profile, create kv cache, warmup model) took 69.67 seconds
(EngineCore pid=8860) INFO 07-31 04:00:02 [vllm.py:790] Asynchronous scheduling is enabled.
04:00:19 | INFO    | stage1 | 20/20  (1.17 q/s, ETA 0 min)
04:00:19 | INFO    | stage1 | TOTAL 20 | success 11 (55.0%) | FAILED 9
04:00:19 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=8860) INFO 07-31 04:00:20 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=8860) INFO 07-31 04:00:20 [core.py:1233] Shutdown complete
[rank0]:[W731 04:00:20.309859463 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())


============================================================
  run_uncertainty
============================================================
04:00:24 | INFO    | stage2 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:00:24 | INFO    | stage2 | Math metrics: 20 of 20 trajectories to do
04:00:24 | INFO    | stage2 | Math metrics done.
04:00:24 | INFO    | stage2 | Sampling metrics: 9 of 9 failed trajectories
04:00:26 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-31 04:00:29.605543: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 04:00:29.676755: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-31 04:00:39 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}

In [8]:
# Check smoke test produced output
import glob
tables = glob.glob('outputs/tables/*') + glob.glob('/content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/tables/*')
figs = glob.glob('outputs/figures/*') + glob.glob('/content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/figures/*')
print(f'Tables: {len(tables)}, Figures: {len(figs)}')
if tables or figs:
    print('Smoke test PASSED — safe to run the full pipeline below.')
else:
    print('WARNING: No outputs found. Check the logs above for errors.')

Tables: 4, Figures: 0
Smoke test PASSED — safe to run the full pipeline below.

---
## Full Pipeline (500 questions)

Only run these cells after the smoke test passes. To reset and run fresh, delete the `data/processed/` folder.

### Stage 0: Download 2WikiMultiHopQA

In [9]:
!python scripts/run_setup.py --config {CONFIG}

04:12:35 | INFO    | setup | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:12:35 | INFO    | setup | Dataset: 2wikimultihopqa (file: 2wikimultihop_dev.json)
04:12:35 | INFO    | setup | Dataset already present: /content/drive/MyDrive/agent-repair-2wikimultihopqa/data/raw/2wikimultihop_dev.json
04:12:36 | INFO    | setup | Dataset ready: /content/drive/MyDrive/agent-repair-2wikimultihopqa/data/raw/2wikimultihop_dev.json (64.2 MB, 12576 questions)
04:12:36 | INFO    | setup | Output dirs created under: /content/drive/MyDrive/agent-repair-2wikimultihopqa

### Stage 1: Generate ReAct Trajectories

In [10]:
!python scripts/run_generate.py --config {CONFIG}

04:12:37 | INFO    | stage1 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:12:37 | INFO    | stage1 | Dataset: 2wikimultihopqa (env: WikiMultiHopEnv)
04:12:37 | INFO    | stage1 | Pool: 500 questions
04:12:37 | INFO    | stage1 | To process: 480 of 500 (20 already done)
04:12:39 | INFO    | stage1 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-31 04:12:42.326789: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 04:12:42.399998: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-31 04:12:52 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-31 04:12:54 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-31 04:12:54 [model.py:1678] Using max model len 8192
INFO 07-31 04:12:55 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-31 04:12:55 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:01<00:00,  4.18it/s]
INFO 07-31 04:12:57 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-31 04:12:59 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=14224) INFO 07-31 04:13:17 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=14224) INFO 07-31 04:13:17 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:58031 backend=nccl
(EngineCore pid=14224) INFO 07-31 04:13:17 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=14224) INFO 07-31 04:13:18 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=14224) INFO 07-31 04:13:19 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=14224) INFO 07-31 04:13:19 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=14224) INFO 07-31 04:13:19 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=14224) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=14224) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=14224) INFO 07-31 04:13:27 [default_loader.py:384] Loading weights took 5.84 seconds
(EngineCore pid=14224) INFO 07-31 04:13:32 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.911639 seconds
(EngineCore pid=14224) INFO 07-31 04:13:40 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=14224) INFO 07-31 04:13:40 [backends.py:1111] Dynamo bytecode transform time: 7.97 s
(EngineCore pid=14224) INFO 07-31 04:13:44 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.030 s
(EngineCore pid=14224) INFO 07-31 04:13:44 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=14224) INFO 07-31 04:13:44 [monitor.py:48] torch.compile took 12.18 s in total
(EngineCore pid=14224) INFO 07-31 04:13:47 [monitor.py:76] Initial profiling/warmup run took 3.01 s
(EngineCore pid=14224) INFO 07-31 04:13:48 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=14224) INFO 07-31 04:13:48 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=14224) INFO 07-31 04:13:51 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=14224) INFO 07-31 04:13:51 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=14224) INFO 07-31 04:13:51 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=14224) INFO 07-31 04:13:51 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=14224) INFO 07-31 04:13:51 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.15it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.81it/s]
(EngineCore pid=14224) INFO 07-31 04:14:03 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=14224) INFO 07-31 04:14:03 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=14224) INFO 07-31 04:14:04 [core.py:283] init engine (profile, create kv cache, warmup model) took 31.97 seconds
(EngineCore pid=14224) INFO 07-31 04:14:06 [vllm.py:790] Asynchronous scheduling is enabled.
04:14:26 | INFO    | stage1 | 32/480  (1.62 q/s, ETA 5 min)
04:14:44 | INFO    | stage1 | 64/480  (1.68 q/s, ETA 4 min)
04:15:02 | INFO    | stage1 | 96/480  (1.73 q/s, ETA 4 min)
04:15:19 | INFO    | stage1 | 128/480  (1.76 q/s, ETA 3 min)
04:15:36 | INFO    | stage1 | 160/480  (1.78 q/s, ETA 3 min)
04:15:55 | INFO    | stage1 | 192/480  (1.76 q/s, ETA 3 min)
04:16:13 | INFO    | stage1 | 224/480  (1.76 q/s, ETA 2 min)
04:16:32 | INFO    | stage1 | 256/480  (1.75 q/s, ETA 2 min)
04:16:54 | INFO    | stage1 | 288/480  (1.71 q/s, ETA 2 min)
04:17:11 | INFO    | stage1 | 320/480  (1.73 q/s, ETA 2 min)
04:17:28 | INFO    | stage1 | 352/480  (1.74 q/s, ETA 1 min)
04:17:47 | INFO    | stage1 | 384/480  (1.74 q/s, ETA 1 min)
04:18:05 | INFO    | stage1 | 416/480  (1.74 q/s, ETA 1 min)
04:18:24 | INFO    | stage1 | 448/480  (1.73 q/s, ETA 0 min)
04:18:44 | INFO    | stage1 | 480/480  (1.73 q/s, ETA 0 min)
04:18:47 | INFO    | stage1 | TOTAL 500 | success 297 (59.4%) | FAILED 203
04:18:47 | INFO    | stage1 | Wrote failed_ids.json — input for Stages 2-5.
(EngineCore pid=14224) INFO 07-31 04:18:47 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=14224) INFO 07-31 04:18:47 [core.py:1233] Shutdown complete
[rank0]:[W731 04:18:47.950987601 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 2: Step-Level Uncertainty

In [11]:
!python scripts/run_uncertainty.py --config {CONFIG}

04:18:52 | INFO    | stage2 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:18:52 | INFO    | stage2 | Math metrics: 480 of 500 trajectories to do
04:19:04 | INFO    | stage2 | Math metrics done.
04:19:04 | INFO    | stage2 | Sampling metrics: 194 of 203 failed trajectories
04:19:06 | INFO    | stage2 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-31 04:19:09.537315: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 04:19:09.610038: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-31 04:19:20 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-31 04:19:21 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-31 04:19:21 [model.py:1678] Using max model len 8192
INFO 07-31 04:19:23 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-31 04:19:23 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.67it/s]
INFO 07-31 04:19:24 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-31 04:19:26 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=16627) INFO 07-31 04:19:44 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=16627) INFO 07-31 04:19:44 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:45421 backend=nccl
(EngineCore pid=16627) INFO 07-31 04:19:44 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=16627) INFO 07-31 04:19:45 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=16627) INFO 07-31 04:19:45 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=16627) INFO 07-31 04:19:46 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=16627) INFO 07-31 04:19:46 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=16627) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=16627) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=16627) INFO 07-31 04:19:54 [default_loader.py:384] Loading weights took 5.87 seconds
(EngineCore pid=16627) INFO 07-31 04:19:58 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 11.842623 seconds
(EngineCore pid=16627) INFO 07-31 04:20:07 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=16627) INFO 07-31 04:20:07 [backends.py:1111] Dynamo bytecode transform time: 7.92 s
(EngineCore pid=16627) INFO 07-31 04:20:11 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.024 s
(EngineCore pid=16627) INFO 07-31 04:20:11 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=16627) INFO 07-31 04:20:11 [monitor.py:48] torch.compile took 12.11 s in total
(EngineCore pid=16627) INFO 07-31 04:20:14 [monitor.py:76] Initial profiling/warmup run took 3.03 s
(EngineCore pid=16627) INFO 07-31 04:20:15 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=16627) INFO 07-31 04:20:15 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=16627) INFO 07-31 04:20:18 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=16627) INFO 07-31 04:20:18 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=16627) INFO 07-31 04:20:18 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=16627) INFO 07-31 04:20:18 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=16627) INFO 07-31 04:20:18 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.12it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.61it/s]
(EngineCore pid=16627) INFO 07-31 04:20:30 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=16627) INFO 07-31 04:20:30 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=16627) INFO 07-31 04:20:30 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.06 seconds
(EngineCore pid=16627) INFO 07-31 04:20:33 [vllm.py:790] Asynchronous scheduling is enabled.
04:21:01 | INFO    | stage2 | 16/194  (0.56 q/s, ETA 5 min)
04:21:26 | INFO    | stage2 | 32/194  (0.60 q/s, ETA 5 min)
04:21:49 | INFO    | stage2 | 48/194  (0.63 q/s, ETA 4 min)
04:22:14 | INFO    | stage2 | 64/194  (0.63 q/s, ETA 3 min)
04:22:41 | INFO    | stage2 | 80/194  (0.63 q/s, ETA 3 min)
04:23:08 | INFO    | stage2 | 96/194  (0.62 q/s, ETA 3 min)
04:23:36 | INFO    | stage2 | 112/194  (0.61 q/s, ETA 2 min)
04:23:57 | INFO    | stage2 | 128/194  (0.63 q/s, ETA 2 min)
04:24:19 | INFO    | stage2 | 144/194  (0.64 q/s, ETA 1 min)
04:24:47 | INFO    | stage2 | 160/194  (0.63 q/s, ETA 1 min)
04:25:14 | INFO    | stage2 | 176/194  (0.63 q/s, ETA 0 min)
04:25:33 | INFO    | stage2 | 192/194  (0.64 q/s, ETA 0 min)
04:25:36 | INFO    | stage2 | 194/194  (0.64 q/s, ETA 0 min)
04:25:36 | INFO    | stage2 | Sampling-based uncertainty done.
(EngineCore pid=16627) INFO 07-31 04:25:36 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=16627) INFO 07-31 04:25:36 [core.py:1233] Shutdown complete
[rank0]:[W731 04:25:36.501851126 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 3: Error Annotation (72B Judge)

In [12]:
!python scripts/run_annotate.py --config {CONFIG}

04:25:40 | INFO    | stage3 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:25:40 | INFO    | stage3 | To annotate: 194 of 203 failed trajectories
04:25:42 | INFO    | stage3 | GPU VRAM: 85.094825984 GB | judge: Qwen/Qwen2.5-72B-Instruct-AWQ (85 GB -> 72B judge)
2026-07-31 04:25:45.457656: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 04:25:45.529250: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-31 04:25:56 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'gpu_memory_utilization': 0.92, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-72B-Instruct-AWQ'}
INFO 07-31 04:25:57 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-31 04:25:57 [model.py:1678] Using max model len 8192
INFO 07-31 04:25:59 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-31 04:25:59 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 11/11 [00:00<00:00, 11.19it/s]
INFO 07-31 04:26:00 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-31 04:26:02 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=18581) INFO 07-31 04:26:20 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-72B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-72B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-72B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=18581) INFO 07-31 04:26:20 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:42155 backend=nccl
(EngineCore pid=18581) INFO 07-31 04:26:20 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=18581) INFO 07-31 04:26:21 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-72B-Instruct-AWQ...
(EngineCore pid=18581) INFO 07-31 04:26:22 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=18581) INFO 07-31 04:26:22 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=18581) INFO 07-31 04:26:22 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=18581) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=18581) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 11/11 [00:13<00:00,  1.25s/it]
(EngineCore pid=18581) INFO 07-31 04:26:38 [default_loader.py:384] Loading weights took 13.90 seconds
(EngineCore pid=18581) INFO 07-31 04:26:48 [gpu_model_runner.py:4820] Model loading took 38.77 GiB memory and 25.640234 seconds
(EngineCore pid=18581) INFO 07-31 04:26:58 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/53d20b985e/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=18581) INFO 07-31 04:26:58 [backends.py:1111] Dynamo bytecode transform time: 9.43 s
(EngineCore pid=18581) INFO 07-31 04:27:04 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.715 s
(EngineCore pid=18581) INFO 07-31 04:27:04 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/bfecb0b875229f090c0ca3328404a3eb2f6add3eda8c9a9377d884ffa1bb6e0d/rank_0_0/model
(EngineCore pid=18581) INFO 07-31 04:27:04 [monitor.py:48] torch.compile took 14.71 s in total
(EngineCore pid=18581) INFO 07-31 04:27:10 [monitor.py:76] Initial profiling/warmup run took 6.45 s
(EngineCore pid=18581) INFO 07-31 04:27:21 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=18581) INFO 07-31 04:27:21 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=18581) INFO 07-31 04:27:24 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.31 GiB total
(EngineCore pid=18581) INFO 07-31 04:27:25 [gpu_worker.py:436] Available KV cache memory: 32.24 GiB
(EngineCore pid=18581) INFO 07-31 04:27:25 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9200 to 0.9365 to maintain the same effective KV cache size.
(EngineCore pid=18581) INFO 07-31 04:27:25 [kv_cache_utils.py:1319] GPU KV cache size: 105,648 tokens
(EngineCore pid=18581) INFO 07-31 04:27:25 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 12.90x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:12<00:00,  4.02it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:05<00:00,  5.91it/s]
(EngineCore pid=18581) INFO 07-31 04:27:45 [gpu_model_runner.py:6046] Graph capturing finished in 20 secs, took 1.17 GiB
(EngineCore pid=18581) INFO 07-31 04:27:45 [gpu_worker.py:597] CUDA graph pool memory: 1.17 GiB (actual), 1.31 GiB (estimated), difference: 0.14 GiB (12.2%).
(EngineCore pid=18581) INFO 07-31 04:27:45 [core.py:283] init engine (profile, create kv cache, warmup model) took 56.51 seconds
(EngineCore pid=18581) INFO 07-31 04:27:47 [vllm.py:790] Asynchronous scheduling is enabled.
04:28:05 | INFO    | stage3 | 16/194  (0.88 traj/s, ETA 3 min)
04:28:22 | INFO    | stage3 | 32/194  (0.92 traj/s, ETA 3 min)
04:28:37 | INFO    | stage3 | 48/194  (0.96 traj/s, ETA 3 min)
04:28:53 | INFO    | stage3 | 64/194  (0.97 traj/s, ETA 2 min)
04:29:10 | INFO    | stage3 | 80/194  (0.97 traj/s, ETA 2 min)
04:29:28 | INFO    | stage3 | 96/194  (0.95 traj/s, ETA 2 min)
04:29:46 | INFO    | stage3 | 112/194  (0.94 traj/s, ETA 1 min)
04:30:00 | INFO    | stage3 | 128/194  (0.96 traj/s, ETA 1 min)
04:30:15 | INFO    | stage3 | 144/194  (0.97 traj/s, ETA 1 min)
04:30:33 | INFO    | stage3 | 160/194  (0.97 traj/s, ETA 1 min)
04:30:50 | INFO    | stage3 | 176/194  (0.96 traj/s, ETA 0 min)
04:31:04 | INFO    | stage3 | 192/194  (0.98 traj/s, ETA 0 min)
04:31:07 | INFO    | stage3 | 194/194  (0.97 traj/s, ETA 0 min)
04:31:08 | INFO    | stage3 | Annotated: 203
04:31:08 | INFO    | stage3 | error types: Counter({'premature_or_wrong_answer': 76, 'wrong_fact_extraction': 52, 'faulty_reasoning': 40, 'wrong_search_query': 35})
04:31:08 | INFO    | stage3 | sources    : Counter({'judge': 203})
04:31:08 | INFO    | stage3 | Next: run `python scripts/label_human.py` to hand-label 50 and check agreement.
(EngineCore pid=18581) INFO 07-31 04:31:08 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=18581) INFO 07-31 04:31:08 [core.py:1233] Shutdown complete
[rank0]:[W731 04:31:08.555928602 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 4: Localization Scoring

In [13]:
!python scripts/run_localize.py --config {CONFIG}

04:31:13 | INFO    | stage4 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:31:14 | INFO    | stage4 | records: 2030 (203 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.404           0.591  0.581          0.335              0.557     0.562     0.700  203
token_entropy_max             0.246           0.512  0.486          0.276              0.591     0.453     0.660  203
max_token_prob_max            0.232           0.507  0.484          0.266              0.591     0.468     0.695  203
token_entropy_mean_k50        0.177           0.374  0.418          0.192              0.438     0.305     0.581  203
token_entropy_mean            0.177           0.374  0.418          0.192              0.438     0.305     0.581  203
token_entropy_mean_k20        0.177           0.374  0.418          0.192              0.438     0.305     0.581  203
token_entropy_mean_k5         0.177           0.389  0.423          0.212              0.473     0.320     0.596  203
perplexity                    0.167           0.409  0.418          0.192              0.483     0.320     0.581  203
max_token_prob_mean           0.153           0.379  0.412          0.187              0.473     0.320     0.596  203
verbalized_confidence         0.059           0.177  0.334          0.103              0.217     0.177     0.586  203
04:31:14 | INFO    | stage4 | Random top-1 baseline: 0.236 | best metric: self_consistency (0.404)
04:31:14 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/tables/localization_summary.csv

### Stage 5: Repair (126 Strategies)

In [14]:
!python scripts/run_repair.py --config {CONFIG}

04:31:14 | INFO    | stage5 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
04:31:14 | INFO    | stage5 | Dataset: 2wikimultihopqa (env: WikiMultiHopEnv)
04:31:14 | INFO    | stage5 | 203 failed x 126 strategies x 3 seeds = 76734 result rows (actual GPU runs are far fewer: dedup)
04:31:16 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-31 04:31:19.646470: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 04:31:19.717656: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-31 04:31:30 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-31 04:31:32 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-31 04:31:32 [model.py:1678] Using max model len 8192
INFO 07-31 04:31:33 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-31 04:31:33 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  5.98it/s]
INFO 07-31 04:31:35 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-31 04:31:36 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=20299) INFO 07-31 04:31:54 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=20299) INFO 07-31 04:31:55 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:38055 backend=nccl
(EngineCore pid=20299) INFO 07-31 04:31:55 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=20299) INFO 07-31 04:31:55 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=20299) INFO 07-31 04:31:56 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=20299) INFO 07-31 04:31:57 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=20299) INFO 07-31 04:31:57 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=20299) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=20299) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=20299) INFO 07-31 04:32:04 [default_loader.py:384] Loading weights took 5.88 seconds
(EngineCore pid=20299) INFO 07-31 04:32:09 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 12.190685 seconds
(EngineCore pid=20299) INFO 07-31 04:32:18 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=20299) INFO 07-31 04:32:18 [backends.py:1111] Dynamo bytecode transform time: 8.05 s
(EngineCore pid=20299) INFO 07-31 04:32:22 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 2.995 s
(EngineCore pid=20299) INFO 07-31 04:32:22 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=20299) INFO 07-31 04:32:22 [monitor.py:48] torch.compile took 12.22 s in total
(EngineCore pid=20299) INFO 07-31 04:32:25 [monitor.py:76] Initial profiling/warmup run took 3.01 s
(EngineCore pid=20299) INFO 07-31 04:32:26 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=20299) INFO 07-31 04:32:26 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=20299) INFO 07-31 04:32:29 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=20299) INFO 07-31 04:32:29 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=20299) INFO 07-31 04:32:29 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=20299) INFO 07-31 04:32:29 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=20299) INFO 07-31 04:32:29 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.04it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.56it/s]
(EngineCore pid=20299) INFO 07-31 04:32:41 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=20299) INFO 07-31 04:32:41 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=20299) INFO 07-31 04:32:42 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.27 seconds
(EngineCore pid=20299) INFO 07-31 04:32:44 [vllm.py:790] Asynchronous scheduling is enabled.
04:32:44 | INFO    | stage5 | --- seed 0 ---
04:39:25 | INFO    | stage5 | seed 0: 64/203 questions | 645 GPU repairs so far | 6.7 min elapsed
04:46:16 | INFO    | stage5 | seed 0: 128/203 questions | 1279 GPU repairs so far | 13.5 min elapsed
04:52:38 | INFO    | stage5 | seed 0: 192/203 questions | 1892 GPU repairs so far | 19.9 min elapsed
04:53:18 | INFO    | stage5 | seed 0: 203/203 questions | 1968 GPU repairs so far | 20.6 min elapsed
04:53:18 | INFO    | stage5 | --- seed 1 ---
05:00:20 | INFO    | stage5 | seed 1: 64/203 questions | 2614 GPU repairs so far | 27.6 min elapsed
05:07:21 | INFO    | stage5 | seed 1: 128/203 questions | 3248 GPU repairs so far | 34.6 min elapsed
05:13:48 | INFO    | stage5 | seed 1: 192/203 questions | 3860 GPU repairs so far | 41.1 min elapsed
05:14:28 | INFO    | stage5 | seed 1: 203/203 questions | 3936 GPU repairs so far | 41.7 min elapsed
05:14:28 | INFO    | stage5 | --- seed 2 ---
05:21:14 | INFO    | stage5 | seed 2: 64/203 questions | 4578 GPU repairs so far | 48.5 min elapsed
05:28:15 | INFO    | stage5 | seed 2: 128/203 questions | 5215 GPU repairs so far | 55.5 min elapsed
05:34:42 | INFO    | stage5 | seed 2: 192/203 questions | 5828 GPU repairs so far | 62.0 min elapsed
05:35:22 | INFO    | stage5 | seed 2: 203/203 questions | 5904 GPU repairs so far | 62.6 min elapsed
05:35:22 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 5904 (vs 76734 result rows — dedup saved 92%)
05:35:22 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/repairs/results.jsonl
(EngineCore pid=20299) INFO 07-31 05:35:22 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=20299) INFO 07-31 05:35:22 [core.py:1233] Shutdown complete
[rank0]:[W731 05:35:22.891931812 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

### Stage 6: Evaluation

In [15]:
!python scripts/run_eval.py --config {CONFIG}

05:35:27 | INFO    | stage6 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
05:35:29 | INFO    | stage6 | rows: 77343 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%     95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step     19.2 16.3-22.3%         170            2.36             21.3
                                                       full_restart     20.8 17.7-24.1%         246            4.03              3.0
                                               oracle_targeted__bt2     22.3 19.1-25.8%         234            3.67              3.0
                                     oracle_targeted__bt2__informed     21.8 18.6-25.1%         231            3.63              3.0
                                          oracle_targeted__informed     12.3  9.8-14.9%         177            2.37            100.0
                                    unc__max_token_prob_max__argmax     14.0 11.3-16.8%         161            2.15             23.2
                               unc__max_token_prob_max__argmax__bt2     22.8 19.7-26.3%         215            3.32             10.8
                     unc__max_token_prob_max__argmax__bt2__informed     24.5 21.0-27.9%         211            3.25             10.8
                          unc__max_token_prob_max__argmax__informed     17.4 14.4-20.5%         161            2.17             23.2
                          unc__max_token_prob_max__cascade_gradient     13.1 10.5-15.9%         170            2.27             38.4
                     unc__max_token_prob_max__cascade_gradient__bt2     22.0 18.7-25.3%         226            3.48              6.9
           unc__max_token_prob_max__cascade_gradient__bt2__informed     24.1 20.8-27.6%         224            3.47              6.9
                unc__max_token_prob_max__cascade_gradient__informed     15.8 13.0-18.7%         170            2.30             38.4
                          unc__max_token_prob_max__cascade_upstream     22.8 19.7-26.3%         215            3.32             10.8
                     unc__max_token_prob_max__cascade_upstream__bt2     25.9 22.5-29.6%         237            3.76              7.4
           unc__max_token_prob_max__cascade_upstream__bt2__informed     24.8 21.5-28.2%         237            3.81              7.4
                unc__max_token_prob_max__cascade_upstream__informed     24.5 21.0-27.9%         211            3.25             10.8
                          unc__max_token_prob_max__cascade_weighted     19.9 16.8-23.2%         210            3.13             15.8
                     unc__max_token_prob_max__cascade_weighted__bt2     24.8 21.5-28.2%         241            3.84              8.4
           unc__max_token_prob_max__cascade_weighted__bt2__informed     24.6 21.3-28.1%         242            3.88              8.4
                unc__max_token_prob_max__cascade_weighted__informed     21.5 18.4-24.8%         207            3.12             15.8
                  unc__max_token_prob_max__earliest_above_threshold     15.1 12.3-18.1%         188            2.62             26.6
             unc__max_token_prob_max__earliest_above_threshold__bt2     24.3 21.0-27.8%         232            3.64             14.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed     24.3 21.0-27.8%         231            3.65             14.8
        unc__max_token_prob_max__earliest_above_threshold__informed     18.6 15.6-21.7%         186            2.64             26.6
                                      unc__max_token_prob_max__topk     21.0 17.9-24.3%         218            3.36             11.8
                                 unc__max_token_prob_max__topk__bt2     25.4 22.0-28.9%         241            3.82              6.9
                       unc__max_token_prob_max__topk__bt2__informed     25.0 21.7-28.4%         242            3.88              6.9
                            unc__max_token_prob_max__topk__informed     22.5 19.2-25.8%         217            3.38             11.8
                                            unc__perplexity__argmax     17.9 14.9-21.0%         165            2.27             16.8
                                       unc__perplexity__argmax__bt2     23.0 19.7-26.4%         215            3.32             10.3
                             unc__perplexity__argmax__bt2__informed     22.8 19.7-26.3%         212            3.28             10.3
                                  unc__perplexity__argmax__informed     19.0 16.1-22.2%         162            2.22             16.8
                                  unc__perplexity__cascade_gradient     14.9 12.2-17.7%         167            2.23             45.3
                             unc__perplexity__cascade_gradient__bt2     23.0 19.7-26.4%         229            3.57              6.4
                   unc__perplexity__cascade_gradient__bt2__informed     22.8 19.5-26.1%         228            3.55              6.4
                        unc__perplexity__cascade_gradient__informed     15.6 12.8-18.6%         171            2.32             45.3
                                  unc__perplexity__cascade_upstream     23.0 19.7-26.4%         215            3.32             10.3
                             unc__perplexity__cascade_upstream__bt2     26.1 22.7-29.7%         239            3.80              6.4
                   unc__perplexity__cascade_upstream__bt2__informed     24.6 21.3-28.1%         236            3.77              6.4
                        unc__perplexity__cascade_upstream__informed     22.8 19.7-26.3%         212            3.28             10.3
                                  unc__perplexity__cascade_weighted     20.4 17.2-23.6%         205            3.09             12.3
                             unc__perplexity__cascade_weighted__bt2     25.0 21.5-28.4%         238            3.78              7.9
                   unc__perplexity__cascade_weighted__bt2__informed     24.8 21.5-28.2%         237            3.77              7.9
                        unc__perplexity__cascade_weighted__informed     21.8 18.7-25.1%         203            3.07             12.3
                          unc__perplexity__earliest_above_threshold     19.9 16.8-23.2%         188            2.68             19.2
                     unc__perplexity__earliest_above_threshold__bt2     24.5 21.2-27.9%         231            3.63             12.3
           unc__perplexity__earliest_above_threshold__bt2__informed     24.8 21.5-28.2%         227            3.57             12.3
                unc__perplexity__earliest_above_threshold__informed     23.2 19.9-26.6%         184            2.64             19.2
                                              unc__perplexity__topk     22.7 19.4-26.1%         214            3.29             10.3
                                         unc__perplexity__topk__bt2     26.3 22.8-29.9%         239            3.80              7.9
                               unc__perplexity__topk__bt2__informed     25.3 22.0-28.7%         238            3.80              7.9
                                    unc__perplexity__topk__informed     23.6 20.4-27.1%         212            3.26             10.3
                                      unc__self_consistency__argmax     10.5  8.2-13.0%         143            1.76             40.4
                                 unc__self_consistency__argmax__bt2     20.8 17.7-24.1%         205            3.09              9.8
                       unc__self_consistency__argmax__bt2__informed     21.5 18.2-24.8%         205            3.08              9.8
                            unc__self_consistency__argmax__informed     12.5 10.0-15.1%         144            1.79             40.4
                            unc__self_consistency__cascade_gradient     11.5  9.0-14.1%         152            1.89             47.8
                       unc__self_consistency__cascade_gradient__bt2     22.2 18.9-25.6%         217            3.29              7.9
             unc__self_consistency__cascade_gradient__bt2__informed     23.0 19.7-26.4%         216            3.27              7.9
                  unc__self_consistency__cascade_gradient__informed     13.8 11.0-16.6%         153            1.91             47.8
                            unc__self_consistency__cascade_upstream     20.8 17.7-24.1%         205            3.09              9.8
                       unc__self_consistency__cascade_upstream__bt2     25.3 21.8-28.7%         235            3.68              6.9
             unc__self_consistency__cascade_upstream__bt2__informed     25.6 22.3-29.1%         234            3.71              6.9
                  unc__self_consistency__cascade_upstream__informed     21.5 18.2-24.8%         205            3.08              9.8
                            unc__self_consistency__cascade_weighted     23.2 19.9-26.6%         208            3.19              6.9
                       unc__self_consistency__cascade_weighted__bt2     25.3 21.8-28.9%         234            3.68             11.3
             unc__self_consistency__cascade_weighted__bt2__informed     24.6 21.3-28.1%         236            3.72             11.3
                  unc__self_consistency__cascade_weighted__informed     23.8 20.4-27.3%         206            3.16              6.9
                    unc__self_consistency__earliest_above_threshold     15.6 12.8-18.6%         175            2.42             33.5
               unc__self_consistency__earliest_above_threshold__bt2     24.0 20.7-27.4%         226            3.54             12.8
     unc__self_consistency__earliest_above_threshold__bt2__informed     24.6 21.3-28.1%         225            3.52             12.8
          unc__self_consistency__earliest_above_threshold__informed     19.4 16.3-22.5%         175            2.43             33.5
                                        unc__self_consistency__topk     22.7 19.4-25.9%         213            3.32              8.4
                                   unc__self_consistency__topk__bt2     25.3 21.8-28.7%         234            3.70              7.9
                         unc__self_consistency__topk__bt2__informed     24.6 21.3-28.1%         235            3.74              7.9
                              unc__self_consistency__topk__informed     24.1 20.8-27.6%         211            3.28              8.4
                                     unc__token_entropy_max__argmax     14.1 11.5-16.9%         161            2.10             24.6
                                unc__token_entropy_max__argmax__bt2     21.7 18.6-25.0%         216            3.35              9.8
                      unc__token_entropy_max__argmax__bt2__informed     24.6 21.2-28.1%         213            3.28              9.8
                           unc__token_entropy_max__argmax__informed     16.9 14.1-20.0%         161            2.16             24.6
                           unc__token_entropy_max__cascade_gradient     15.3 12.5-18.2%         178            2.42             35.0
                      unc__token_entropy_max__cascade_gradient__bt2     22.7 19.4-26.1%         230            3.62              8.9
            unc__token_entropy_max__cascade_gradient__bt2__informed     23.8 20.5-27.3%         228            3.60              8.9
                 unc__token_entropy_max__cascade_gradient__informed     17.4 14.4-20.4%         177            2.44             35.0
                           unc__token_entropy_max__cascade_upstream     21.7 18.6-25.0%         216            3.35              9.8
                      unc__token_entropy_max__cascade_upstream__bt2     25.6 22.2-29.2%         238            3.80              7.9
            unc__token_entropy_max__cascade_upstream__bt2__informed     24.5 21.2-27.9%         238            3.82              7.9
                 unc__token_entropy_max__cascade_upstream__informed     24.6 21.2-28.1%         213            3.28              9.8
                           unc__token_entropy_max__cascade_weighted     19.4 16.3-22.7%         203            2.99             13.8
                      unc__token_entropy_max__cascade_weighted__bt2     24.8 21.5-28.2%         239            3.80              9.8
            unc__token_entropy_max__cascade_weighted__bt2__informed     24.1 20.8-27.6%         238            3.81              9.8
                 unc__token_entropy_max__cascade_weighted__informed     20.2 17.1-23.5%         202            3.02             13.8
                   unc__token_entropy_max__earliest_above_threshold     16.9 14.0-19.9%         184            2.49             27.6
              unc__token_entropy_max__earliest_above_threshold__bt2     23.2 20.0-26.6%         231            3.65             12.8
    unc__token_entropy_max__earliest_above_threshold__bt2__informed     24.3 21.0-27.8%         230            3.62             12.8
         unc__token_entropy_max__earliest_above_threshold__informed     19.9 16.8-23.2%         182            2.52             27.6
                                       unc__token_entropy_max__topk     20.8 17.7-24.1%         214            3.27             10.8
                                  unc__token_entropy_max__topk__bt2     25.6 22.2-29.1%         235            3.70              9.4
                        unc__token_entropy_max__topk__bt2__informed     24.8 21.5-28.2%         236            3.78              9.4
                             unc__token_entropy_max__topk__informed     22.7 19.4-25.9%         210            3.23             10.8
                                 unc__verbalized_confidence__argmax     21.5 18.4-24.8%         176            2.59              5.9
                            unc__verbalized_confidence__argmax__bt2     24.1 20.8-27.6%         210            3.23              6.4
                  unc__verbalized_confidence__argmax__bt2__informed     24.1 20.8-27.6%         208            3.26              6.4
                       unc__verbalized_confidence__argmax__informed     22.3 19.2-25.8%         172            2.54              5.9
                       unc__verbalized_confidence__cascade_gradient     16.6 13.6-19.7%         163            2.17             12.3
                  unc__verbalized_confidence__cascade_gradient__bt2     23.8 20.5-27.3%         216            3.34              8.4
        unc__verbalized_confidence__cascade_gradient__bt2__informed     23.3 20.0-26.8%         214            3.37              8.4
             unc__verbalized_confidence__cascade_gradient__informed     19.0 15.9-22.2%         158            2.13             12.3
                       unc__verbalized_confidence__cascade_upstream     24.1 20.8-27.6%         210            3.23              6.4
                  unc__verbalized_confidence__cascade_upstream__bt2     26.4 23.0-30.0%         231            3.64              6.4
        unc__verbalized_confidence__cascade_upstream__bt2__informed     25.0 21.7-28.4%         233            3.69              6.4
             unc__verbalized_confidence__cascade_upstream__informed     24.1 20.8-27.6%         208            3.26              6.4
                       unc__verbalized_confidence__cascade_weighted     23.2 19.9-26.6%         202            3.08              6.4
                  unc__verbalized_confidence__cascade_weighted__bt2     25.4 22.0-29.1%         228            3.60              5.4
        unc__verbalized_confidence__cascade_weighted__bt2__informed     24.3 21.0-27.8%         226            3.61              5.4
             unc__verbalized_confidence__cascade_weighted__informed     23.5 20.2-26.9%         202            3.11              6.4
               unc__verbalized_confidence__earliest_above_threshold     21.8 18.6-25.1%         200            3.01             10.3
          unc__verbalized_confidence__earliest_above_threshold__bt2     25.1 21.7-28.7%         229            3.60              6.4
unc__verbalized_confidence__earliest_above_threshold__bt2__informed     24.3 21.0-27.8%         226            3.60              6.4
     unc__verbalized_confidence__earliest_above_threshold__informed     23.0 19.7-26.4%         198            3.01             10.3
                                   unc__verbalized_confidence__topk     24.3 21.0-27.8%         215            3.36             11.8
                              unc__verbalized_confidence__topk__bt2     25.4 22.0-28.9%         239            3.81              7.4
                    unc__verbalized_confidence__topk__bt2__informed     24.0 20.7-27.4%         236            3.81              7.4
                         unc__verbalized_confidence__topk__informed     24.5 21.2-27.9%         214            3.36             11.8
                                           uncertainty_ensemble_any     47.0 43.0-50.9%       11423          166.80             89.7
                                                    oracle_targeted     10.0  7.7-12.5%         172            2.26            100.0
Traceback (most recent call last):
  File "/content/agent-repair/scripts/run_eval.py", line 461, in <module>
    main()
  File "/content/agent-repair/scripts/run_eval.py", line 91, in main
    u = df[df.strategy.isin(bt0_strats)] if bt0_strats else df[df.strategy.isin(unc_strats)]
                                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'bt0_strats' where it is not associated with a value

---
## Results

In [16]:
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())
else:
    print('Summary not yet generated. Run Stage 6 first.')

Summary not yet generated. Run Stage 6 first.

In [17]:
import pandas as pd

results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)
else:
    print('Results table not yet generated. Run Stage 6 first.')

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,19.2,16.3-22.3%,170,2.36,21.3
1,full_restart,20.8,17.7-24.1%,246,4.03,3.0
2,oracle_targeted__bt2,22.3,19.1-25.8%,234,3.67,3.0
3,oracle_targeted__bt2__informed,21.8,18.6-25.1%,231,3.63,3.0
4,oracle_targeted__informed,12.3,9.8-14.9%,177,2.37,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,25.4,22.0-28.9%,239,3.81,7.4
123,unc__verbalized_confidence__topk__bt2__informed,24.0,20.7-27.4%,236,3.81,7.4
124,unc__verbalized_confidence__topk__informed,24.5,21.2-27.9%,214,3.36,11.8
125,uncertainty_ensemble_any,47.0,43.0-50.9%,11423,166.80,89.7
126,oracle_targeted,10.0,7.7-12.5%,172,2.26,100.0

In [18]:
import glob
from IPython.display import display, Image

fig_dir = cfg.path('figures')
figs = sorted(glob.glob(os.path.join(fig_dir, '*.png')))
if figs:
    for f in figs:
        print(f'\n--- {os.path.basename(f)} ---')
        display(Image(filename=f, width=800))
else:
    print('No figures yet. Run Stage 6 first.')

No figures yet. Run Stage 6 first.

---
## Re-run Stages 4–6 with Cascade-Aware Strategies

**Use this after you already have stages 1–3 completed** (trajectories, uncertainty, annotations).
This pulls the latest code (with cascade rules), clears only localization/repair/eval outputs,
and re-runs stages 4→5→6 in one cell. ~3-4 hours on A100-80GB for 500 questions.

In [19]:
import os, shutil

REPO_DIR = '/content/agent-repair'
CONFIG = 'config/config_colab_2wikimultihopqa.yaml'

# 1. Pull latest code with cascade-aware strategies
os.chdir(REPO_DIR)
!git pull

# 2. Clear ONLY stages 4-6 outputs (keep trajectories, uncertainty, annotations)
drive_base = '/content/drive/MyDrive/agent-repair-2wikimultihopqa'
for base in [REPO_DIR, drive_base]:
    for d in ['outputs/localization', 'outputs/repairs', 'outputs/tables', 'outputs/figures']:
        p = os.path.join(base, d)
        if os.path.exists(p):
            shutil.rmtree(p)
            print(f'Cleared {p}')

# 3. Clear checkpoint files for stages 4-6 (these live in outputs/logs/)
for base in [REPO_DIR, drive_base]:
    for ckpt in ['outputs/logs/stage4_localize.jsonl',
                 'outputs/logs/stage5_repair.jsonl',
                 'outputs/logs/stage6_eval.jsonl']:
        p = os.path.join(base, ckpt)
        if os.path.exists(p):
            os.remove(p)
            print(f'Removed checkpoint: {p}')

print('\nStages 1-3 data preserved. Ready to re-run 4→5→6.')

Already up to date.
Cleared /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/localization
Cleared /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/repairs
Cleared /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/tables
Cleared /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/figures
Removed checkpoint: /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/logs/stage5_repair.jsonl

Stages 1-3 data preserved. Ready to re-run 4→5→6.

In [20]:
# Run stages 4 → 5 → 6 sequentially (run this and go to sleep)
import time

for stage in ['run_localize', 'run_repair', 'run_eval']:
    t0 = time.time()
    print(f'\n{"="*60}\n  {stage}\n{"="*60}')
    !python scripts/{stage}.py --config {CONFIG}
    elapsed = (time.time() - t0) / 60
    print(f'  ✓ {stage} done in {elapsed:.1f} min\n')

print('\n' + '='*60)
print('  ALL DONE — check results below')
print('='*60)

============================================================
  run_localize
============================================================
05:35:38 | INFO    | stage4 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
05:35:39 | INFO    | stage4 | records: 2030 (203 trajectories x 10 metrics)
                        argmax_top1  argmax_within1    mrr  threshold_hit  threshold_within1  top2_hit  top3_hit    n
metric
self_consistency              0.404           0.591  0.581          0.335              0.557     0.562     0.700  203
token_entropy_max             0.246           0.512  0.486          0.276              0.591     0.453     0.660  203
max_token_prob_max            0.232           0.507  0.484          0.266              0.591     0.468     0.695  203
token_entropy_mean_k50        0.177           0.374  0.418          0.192              0.438     0.305     0.581  203
token_entropy_mean            0.177           0.374  0.418          0.192              0.438     0.305     0.581  203
token_entropy_mean_k20        0.177           0.374  0.418          0.192              0.438     0.305     0.581  203
token_entropy_mean_k5         0.177           0.389  0.423          0.212              0.473     0.320     0.596  203
perplexity                    0.167           0.409  0.418          0.192              0.483     0.320     0.581  203
max_token_prob_mean           0.153           0.379  0.412          0.187              0.473     0.320     0.596  203
verbalized_confidence         0.059           0.177  0.334          0.103              0.217     0.177     0.586  203
05:35:39 | INFO    | stage4 | Random top-1 baseline: 0.236 | best metric: self_consistency (0.404)
05:35:39 | INFO    | stage4 | Saved /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/tables/localization_summary.csv
  ✓ run_localize done in 0.0 min


============================================================
  run_repair
============================================================
05:35:40 | INFO    | stage5 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
05:35:40 | INFO    | stage5 | Dataset: 2wikimultihopqa (env: WikiMultiHopEnv)
05:35:40 | INFO    | stage5 | 203 failed x 126 strategies x 3 seeds = 76734 result rows (actual GPU runs are far fewer: dedup)
05:35:42 | INFO    | stage5 | GPU VRAM: 85.094825984 GB | agent model: Qwen/Qwen2.5-32B-Instruct-AWQ (85 GB -> fp16)
2026-07-31 05:35:45.462372: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-07-31 05:35:45.534654: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO 07-31 05:35:56 [utils.py:233] non-default args: {'trust_remote_code': True, 'seed': 42, 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-32B-Instruct-AWQ'}
INFO 07-31 05:35:58 [model.py:549] Resolved architecture: Qwen2ForCausalLM
INFO 07-31 05:35:58 [model.py:1678] Using max model len 8192
INFO 07-31 05:35:59 [awq_marlin.py:245] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 07-31 05:35:59 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=8192.
Parse safetensors files: 100% 5/5 [00:00<00:00,  6.21it/s]
INFO 07-31 05:36:01 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 07-31 05:36:02 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=37445) INFO 07-31 05:36:20 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=42, served_model_name=Qwen/Qwen2.5-32B-Instruct-AWQ, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=37445) INFO 07-31 05:36:21 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:59413 backend=nccl
(EngineCore pid=37445) INFO 07-31 05:36:21 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=37445) INFO 07-31 05:36:22 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen2.5-32B-Instruct-AWQ...
(EngineCore pid=37445) INFO 07-31 05:36:22 [awq_marlin.py:408] Using MarlinLinearKernel for AWQMarlinLinearMethod
(EngineCore pid=37445) INFO 07-31 05:36:23 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=37445) INFO 07-31 05:36:23 [flash_attn.py:596] Using FlashAttention version 2
(EngineCore pid=37445) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=37445) <frozen importlib._bootstrap_external>:1301: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.
Loading safetensors checkpoint shards: 100% 5/5 [00:05<00:00,  1.16s/it]
(EngineCore pid=37445) INFO 07-31 05:36:31 [default_loader.py:384] Loading weights took 5.87 seconds
(EngineCore pid=37445) INFO 07-31 05:36:35 [gpu_model_runner.py:4820] Model loading took 18.14 GiB memory and 12.068816 seconds
(EngineCore pid=37445) INFO 07-31 05:36:44 [backends.py:1051] Using cache directory: /root/.cache/vllm/torch_compile_cache/dba43f1a5b/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=37445) INFO 07-31 05:36:44 [backends.py:1111] Dynamo bytecode transform time: 8.06 s
(EngineCore pid=37445) INFO 07-31 05:36:48 [backends.py:285] Directly load the compiled graph(s) for compile range (1, 8192) from the cache, took 3.066 s
(EngineCore pid=37445) INFO 07-31 05:36:48 [decorators.py:303] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/6edd1661dc90e5e21f0b322becd3da52d48396b094807d6cd4f8b78c8793c83d/rank_0_0/model
(EngineCore pid=37445) INFO 07-31 05:36:48 [monitor.py:48] torch.compile took 12.31 s in total
(EngineCore pid=37445) INFO 07-31 05:36:51 [monitor.py:76] Initial profiling/warmup run took 3.03 s
(EngineCore pid=37445) INFO 07-31 05:36:52 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=37445) INFO 07-31 05:36:52 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=51 (largest=512), FULL=35 (largest=256)
(EngineCore pid=37445) INFO 07-31 05:36:55 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.00 GiB total
(EngineCore pid=37445) INFO 07-31 05:36:55 [gpu_worker.py:436] Available KV cache memory: 51.53 GiB
(EngineCore pid=37445) INFO 07-31 05:36:55 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.9000 to 0.9126 to maintain the same effective KV cache size.
(EngineCore pid=37445) INFO 07-31 05:36:55 [kv_cache_utils.py:1319] GPU KV cache size: 211,056 tokens
(EngineCore pid=37445) INFO 07-31 05:36:55 [kv_cache_utils.py:1324] Maximum concurrency for 8,192 tokens per request: 25.76x
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100% 51/51 [00:07<00:00,  7.10it/s]
Capturing CUDA graphs (decode, FULL): 100% 35/35 [00:03<00:00,  9.66it/s]
(EngineCore pid=37445) INFO 07-31 05:37:07 [gpu_model_runner.py:6046] Graph capturing finished in 12 secs, took 0.90 GiB
(EngineCore pid=37445) INFO 07-31 05:37:07 [gpu_worker.py:597] CUDA graph pool memory: 0.9 GiB (actual), 1.0 GiB (estimated), difference: 0.1 GiB (11.5%).
(EngineCore pid=37445) INFO 07-31 05:37:08 [core.py:283] init engine (profile, create kv cache, warmup model) took 32.28 seconds
(EngineCore pid=37445) INFO 07-31 05:37:10 [vllm.py:790] Asynchronous scheduling is enabled.
05:37:10 | INFO    | stage5 | --- seed 0 ---
05:44:04 | INFO    | stage5 | seed 0: 64/203 questions | 671 GPU repairs so far | 6.9 min elapsed
05:51:19 | INFO    | stage5 | seed 0: 128/203 questions | 1342 GPU repairs so far | 14.2 min elapsed
05:58:00 | INFO    | stage5 | seed 0: 192/203 questions | 1982 GPU repairs so far | 20.8 min elapsed
05:58:40 | INFO    | stage5 | seed 0: 203/203 questions | 2065 GPU repairs so far | 21.5 min elapsed
05:58:40 | INFO    | stage5 | --- seed 1 ---
06:05:52 | INFO    | stage5 | seed 1: 64/203 questions | 2738 GPU repairs so far | 28.7 min elapsed
06:13:13 | INFO    | stage5 | seed 1: 128/203 questions | 3409 GPU repairs so far | 36.0 min elapsed
06:19:58 | INFO    | stage5 | seed 1: 192/203 questions | 4048 GPU repairs so far | 42.8 min elapsed
06:20:38 | INFO    | stage5 | seed 1: 203/203 questions | 4131 GPU repairs so far | 43.5 min elapsed
06:20:38 | INFO    | stage5 | --- seed 2 ---
06:27:41 | INFO    | stage5 | seed 2: 64/203 questions | 4799 GPU repairs so far | 50.5 min elapsed
06:35:13 | INFO    | stage5 | seed 2: 128/203 questions | 5473 GPU repairs so far | 58.1 min elapsed
06:42:04 | INFO    | stage5 | seed 2: 192/203 questions | 6113 GPU repairs so far | 64.9 min elapsed
06:42:44 | INFO    | stage5 | seed 2: 203/203 questions | 6196 GPU repairs so far | 65.6 min elapsed
06:42:44 | INFO    | stage5 | Repair complete. Actual GPU repair runs: 6196 (vs 76734 result rows — dedup saved 92%)
06:42:44 | INFO    | stage5 | Results -> /content/drive/MyDrive/agent-repair-2wikimultihopqa/outputs/repairs/results.jsonl
(EngineCore pid=37445) INFO 07-31 06:42:44 [core.py:1210] Shutdown initiated (timeout=0)
(EngineCore pid=37445) INFO 07-31 06:42:44 [core.py:1233] Shutdown complete
[rank0]:[W731 06:42:44.049238587 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
  ✓ run_repair done in 67.1 min


============================================================
  run_eval
============================================================
06:42:49 | INFO    | stage6 | config=config/config_colab_2wikimultihopqa.yaml  base=/content/drive/MyDrive/agent-repair-2wikimultihopqa
06:42:51 | INFO    | stage6 | rows: 77343 | uncertainty strategies: 120 (bt0: 60) | + ensemble

==============================================================================
MAIN RESULTS  (fixed_% = share of FAILED trajectories that the repair fixed)
==============================================================================
                                                           strategy  fixed_%     95%_CI  avg_tokens  avg_tool_calls  hit_true_step_%
                                                        random_step     19.0 15.9-22.2%         170            2.36             21.3
                                                       full_restart     21.2 18.1-24.5%         246            4.03              3.0
                                               oracle_targeted__bt2     22.0 18.7-25.3%         234            3.68              3.0
                                     oracle_targeted__bt2__informed     21.0 17.9-24.3%         230            3.63              3.0
                                          oracle_targeted__informed     12.2  9.5-14.8%         177            2.37            100.0
                                    unc__max_token_prob_max__argmax     13.8 11.2-16.6%         162            2.16             23.2
                               unc__max_token_prob_max__argmax__bt2     22.2 18.9-25.4%         215            3.31             10.8
                     unc__max_token_prob_max__argmax__bt2__informed     24.1 20.7-27.6%         211            3.26             10.8
                          unc__max_token_prob_max__argmax__informed     17.7 14.8-20.8%         161            2.16             23.2
                          unc__max_token_prob_max__cascade_gradient     12.8 10.2-15.4%         171            2.27             38.4
                     unc__max_token_prob_max__cascade_gradient__bt2     21.3 18.1-24.6%         226            3.50              6.9
           unc__max_token_prob_max__cascade_gradient__bt2__informed     23.8 20.4-27.3%         223            3.48              6.9
                unc__max_token_prob_max__cascade_gradient__informed     15.6 12.8-18.6%         170            2.29             38.4
                          unc__max_token_prob_max__cascade_upstream     22.2 18.9-25.4%         215            3.31             10.8
                     unc__max_token_prob_max__cascade_upstream__bt2     25.0 21.5-28.4%         237            3.77              7.4
           unc__max_token_prob_max__cascade_upstream__bt2__informed     24.3 20.8-27.8%         237            3.81              7.4
                unc__max_token_prob_max__cascade_upstream__informed     24.1 20.7-27.6%         211            3.26             10.8
                          unc__max_token_prob_max__cascade_weighted     19.7 16.6-23.0%         210            3.13             15.8
                     unc__max_token_prob_max__cascade_weighted__bt2     24.1 20.7-27.6%         240            3.84              8.4
           unc__max_token_prob_max__cascade_weighted__bt2__informed     24.1 20.7-27.6%         241            3.88              8.4
                unc__max_token_prob_max__cascade_weighted__informed     21.7 18.4-25.0%         207            3.12             15.8
                  unc__max_token_prob_max__earliest_above_threshold     15.1 12.3-18.1%         189            2.62             26.6
             unc__max_token_prob_max__earliest_above_threshold__bt2     23.6 20.4-27.1%         230            3.63             14.8
   unc__max_token_prob_max__earliest_above_threshold__bt2__informed     23.8 20.5-27.3%         230            3.66             14.8
        unc__max_token_prob_max__earliest_above_threshold__informed     19.0 15.9-22.2%         186            2.62             26.6
                                      unc__max_token_prob_max__topk     20.5 17.2-23.8%         219            3.36             11.8
                                 unc__max_token_prob_max__topk__bt2     24.6 21.2-28.1%         240            3.83              6.9
                       unc__max_token_prob_max__topk__bt2__informed     24.3 21.0-27.8%         241            3.86              6.9
                            unc__max_token_prob_max__topk__informed     22.2 18.9-25.4%         217            3.38             11.8
                                            unc__perplexity__argmax     17.2 14.3-20.2%         166            2.26             16.8
                                       unc__perplexity__argmax__bt2     22.3 19.1-25.6%         215            3.32             10.3
                             unc__perplexity__argmax__bt2__informed     22.2 18.9-25.4%         212            3.27             10.3
                                  unc__perplexity__argmax__informed     19.2 16.1-22.3%         161            2.22             16.8
                                  unc__perplexity__cascade_gradient     14.8 12.0-17.7%         168            2.24             45.3
                             unc__perplexity__cascade_gradient__bt2     22.2 18.9-25.4%         229            3.59              6.4
                   unc__perplexity__cascade_gradient__bt2__informed     22.3 19.1-25.6%         227            3.55              6.4
                        unc__perplexity__cascade_gradient__informed     15.6 12.8-18.4%         172            2.32             45.3
                                  unc__perplexity__cascade_upstream     22.3 19.1-25.6%         215            3.32             10.3
                             unc__perplexity__cascade_upstream__bt2     25.3 21.8-28.7%         239            3.80              6.4
                   unc__perplexity__cascade_upstream__bt2__informed     24.3 20.8-27.8%         235            3.77              6.4
                        unc__perplexity__cascade_upstream__informed     22.2 18.9-25.4%         212            3.27             10.3

In [21]:
# View cascade-aware results
from src.utils import load_config
cfg = load_config(CONFIG)

summary_path = os.path.join(cfg.path('tables'), 'summary.txt')
if os.path.exists(summary_path):
    with open(summary_path) as f:
        print(f.read())

import pandas as pd
results_path = os.path.join(cfg.path('tables'), 'main_results_readable.csv')
if os.path.exists(results_path):
    df = pd.read_csv(results_path)
    display(df)

import glob
from IPython.display import display, Image
figs = sorted(glob.glob(os.path.join(cfg.path('figures'), '*.png')))
for f in figs:
    print(f'\n--- {os.path.basename(f)} ---')
    display(Image(filename=f, width=800))

,strategy,fixed_%,95%_CI,avg_tokens,avg_tool_calls,hit_true_step_%
0,random_step,19.0,15.9-22.2%,170,2.36,21.3
1,full_restart,21.2,18.1-24.5%,246,4.03,3.0
2,oracle_targeted__bt2,22.0,18.7-25.3%,234,3.68,3.0
3,oracle_targeted__bt2__informed,21.0,17.9-24.3%,230,3.63,3.0
4,oracle_targeted__informed,12.2,9.5-14.8%,177,2.37,100.0
...,...,...,...,...,...,...
122,unc__verbalized_confidence__topk__bt2,24.6,21.2-28.1%,239,3.82,7.4
123,unc__verbalized_confidence__topk__bt2__informed,23.6,20.4-27.1%,236,3.82,7.4
124,unc__verbalized_confidence__topk__informed,24.3,21.0-27.8%,213,3.36,11.8
125,uncertainty_ensemble_any,46.0,42.0-49.9%,11426,166.56,89.7
126,oracle_targeted,10.0,7.7-12.5%,171,2.26,100.0